# DeepDriveMD Configuration for KRAS G12D on 8x H100
# --------------------------------------------------

# The simulation input directory. Maps to /experiment/system inside Docker.
# This directory must contain: kras.pdb, kras.prmtop, kras.inpcrd
simulation_input_dir: data/kras

# The number of workers to use.
# On 8x H100, we dedicate 1 worker per GPU.
num_workers: 8

# The number of simulations to run between training jobs.
# 32 sims = 4 runs per GPU * 8 GPUs. This generates a healthy chunk of data per round.
simulations_per_train: 32

# The number of simulations to run between inference jobs.
# Keep this lower to catch outliers quickly.
simulations_per_inference: 8

# The total number of simulations to run before the workflow stops.
# 10,000 gives you plenty of runway for a conference-scale run.
num_total_simulations: 10000

# ----------------------------------------------------------------------
# COMPUTE SETTINGS (Parsl / High Performance Computing)
# ----------------------------------------------------------------------
compute_settings:
  # 'workstation' mode works best for single-node Docker runs
  name: workstation
  
  # We explicitly list all 8 H100 GPUs available on your node.
  available_accelerators: ["0", "1", "2", "3", "4", "5", "6", "7"]

# ----------------------------------------------------------------------
# SIMULATION SETTINGS (OpenMM)
# ----------------------------------------------------------------------
simulation_settings:
  # Run shorter 1ns chunks because H100s are extremely fast. 
  # If this is too long, you wait too long for feedback.
  simulation_length_ns: 1.0
  
  # Save data every 10ps (standard for ML analysis)
  report_interval_ps: 10
  
  # Physiological temperature
  temperature_kelvin: 310
  
  # The solvent type (Explicit is required for valid science on this system size)
  solvent_type: explicit
  
  # The topology file generated by TLeap (Required for explicit solvent)
  topology_file: data/kras/system/kras.prmtop
  
  # The reference PDB for RMSD calculation (The "Active" state target)
  # This tracks if we are getting closer to the ON state.
  rmsd_reference_pdb: data/kras/6VJJ.pdb

# ----------------------------------------------------------------------
# TRAINING SETTINGS (CVAE)
# ----------------------------------------------------------------------
train_settings:
  # Points to the separate config file we created for the neural network architecture
  # This file defines the 169x169 contact map shape.
  cvae_settings_yaml: examples/kras/cvae-prod-settings.yaml

# ----------------------------------------------------------------------
# INFERENCE SETTINGS (Outlier Detection)
# ----------------------------------------------------------------------
inference_settings:
  # Same architecture file as training
  cvae_settings_yaml: examples/kras/cvae-prod-settings.yaml
  
  # How many outliers to pull from the latent space for RMSD sorting.
  # Higher number = broader search.
  num_outliers: 300